// تحويل كود ISO إلى علم إيموجي
export const getFlag = (code) => {
  if (!code || code.length !== 2 || code === "--") return "";
  return String.fromCodePoint(
    0x1F1E6 + code.toUpperCase().charCodeAt(0) - 65,
    0x1F1E6 + code.toUpperCase().charCodeAt(1) - 65
  );
};

// قائمة الدول مع كود الاتصال الدولي — الدول العربية أولاً
const COUNTRIES = [
  { code: "SA", name: "السعودية",            dialCode: "+966" },
  { code: "JO", name: "الأردن",              dialCode: "+962" },
  { code: "PS", name: "فلسطين",              dialCode: "+970" },
  { code: "AE", name: "الإمارات",            dialCode: "+971" },
  { code: "KW", name: "الكويت",              dialCode: "+965" },
  { code: "QA", name: "قطر",                 dialCode: "+974" },
  { code: "BH", name: "البحرين",             dialCode: "+973" },
  { code: "OM", name: "عُمان",               dialCode: "+968" },
  { code: "YE", name: "اليمن",               dialCode: "+967" },
  { code: "IQ", name: "العراق",              dialCode: "+964" },
  { code: "SY", name: "سوريا",               dialCode: "+963" },
  { code: "LB", name: "لبنان",               dialCode: "+961" },
  { code: "EG", name: "مصر",                 dialCode: "+20"  },
  { code: "LY", name: "ليبيا",               dialCode: "+218" },
  { code: "TN", name: "تونس",                dialCode: "+216" },
  { code: "DZ", name: "الجزائر",             dialCode: "+213" },
  { code: "MA", name: "المغرب",              dialCode: "+212" },
  { code: "SD", name: "السودان",             dialCode: "+249" },
  { code: "MR", name: "موريتانيا",           dialCode: "+222" },
  { code: "SO", name: "الصومال",             dialCode: "+252" },
  { code: "DJ", name: "جيبوتي",              dialCode: "+253" },
  { code: "KM", name: "جزر القمر",           dialCode: "+269" },
  { code: "--", name: "──────────────",       dialCode: ""     },
  { code: "AF", name: "أفغانستان",           dialCode: "+93"  },
  { code: "AL", name: "ألبانيا",             dialCode: "+355" },
  { code: "DE", name: "ألمانيا",             dialCode: "+49"  },
  { code: "AR", name: "الأرجنتين",           dialCode: "+54"  },
  { code: "AM", name: "أرمينيا",             dialCode: "+374" },
  { code: "AU", name: "أستراليا",            dialCode: "+61"  },
  { code: "AT", name: "النمسا",              dialCode: "+43"  },
  { code: "AZ", name: "أذربيجان",            dialCode: "+994" },
  { code: "BD", name: "بنغلاديش",            dialCode: "+880" },
  { code: "BE", name: "بلجيكا",              dialCode: "+32"  },
  { code: "BO", name: "بوليفيا",             dialCode: "+591" },
  { code: "BA", name: "البوسنة والهرسك",     dialCode: "+387" },
  { code: "BR", name: "البرازيل",            dialCode: "+55"  },
  { code: "BG", name: "بلغاريا",             dialCode: "+359" },
  { code: "CA", name: "كندا",                dialCode: "+1"   },
  { code: "CL", name: "تشيلي",               dialCode: "+56"  },
  { code: "CN", name: "الصين",               dialCode: "+86"  },
  { code: "CO", name: "كولومبيا",            dialCode: "+57"  },
  { code: "HR", name: "كرواتيا",             dialCode: "+385" },
  { code: "CZ", name: "التشيك",              dialCode: "+420" },
  { code: "DK", name: "الدنمارك",            dialCode: "+45"  },
  { code: "EC", name: "الإكوادور",           dialCode: "+593" },
  { code: "ET", name: "إثيوبيا",             dialCode: "+251" },
  { code: "FI", name: "فنلندا",              dialCode: "+358" },
  { code: "FR", name: "فرنسا",               dialCode: "+33"  },
  { code: "GE", name: "جورجيا",              dialCode: "+995" },
  { code: "GH", name: "غانا",                dialCode: "+233" },
  { code: "GR", name: "اليونان",             dialCode: "+30"  },
  { code: "HU", name: "المجر",               dialCode: "+36"  },
  { code: "IN", name: "الهند",               dialCode: "+91"  },
  { code: "ID", name: "إندونيسيا",           dialCode: "+62"  },
  { code: "IR", name: "إيران",               dialCode: "+98"  },
  { code: "IE", name: "أيرلندا",             dialCode: "+353" },
  { code: "IL", name: "إسرائيل",             dialCode: "+972" },
  { code: "IT", name: "إيطاليا",             dialCode: "+39"  },
  { code: "JP", name: "اليابان",             dialCode: "+81"  },
  { code: "KZ", name: "كازاخستان",           dialCode: "+7"   },
  { code: "KE", name: "كينيا",               dialCode: "+254" },
  { code: "KR", name: "كوريا الجنوبية",      dialCode: "+82"  },
  { code: "MY", name: "ماليزيا",             dialCode: "+60"  },
  { code: "MX", name: "المكسيك",             dialCode: "+52"  },
  { code: "NL", name: "هولندا",              dialCode: "+31"  },
  { code: "NZ", name: "نيوزيلندا",           dialCode: "+64"  },
  { code: "NG", name: "نيجيريا",             dialCode: "+234" },
  { code: "NO", name: "النرويج",             dialCode: "+47"  },
  { code: "PK", name: "باكستان",             dialCode: "+92"  },
  { code: "PE", name: "بيرو",                dialCode: "+51"  },
  { code: "PH", name: "الفلبين",             dialCode: "+63"  },
  { code: "PL", name: "بولندا",              dialCode: "+48"  },
  { code: "PT", name: "البرتغال",            dialCode: "+351" },
  { code: "RO", name: "رومانيا",             dialCode: "+40"  },
  { code: "RU", name: "روسيا",               dialCode: "+7"   },
  { code: "SN", name: "السنغال",             dialCode: "+221" },
  { code: "RS", name: "صربيا",               dialCode: "+381" },
  { code: "SG", name: "سنغافورة",            dialCode: "+65"  },
  { code: "ZA", name: "جنوب أفريقيا",        dialCode: "+27"  },
  { code: "ES", name: "إسبانيا",             dialCode: "+34"  },
  { code: "SE", name: "السويد",              dialCode: "+46"  },
  { code: "CH", name: "سويسرا",              dialCode: "+41"  },
  { code: "TZ", name: "تنزانيا",             dialCode: "+255" },
  { code: "TH", name: "تايلاند",             dialCode: "+66"  },
  { code: "TR", name: "تركيا",               dialCode: "+90"  },
  { code: "UA", name: "أوكرانيا",            dialCode: "+380" },
  { code: "GB", name: "المملكة المتحدة",     dialCode: "+44"  },
  { code: "US", name: "الولايات المتحدة",    dialCode: "+1"   },
  { code: "UZ", name: "أوزبكستان",           dialCode: "+998" },
  { code: "VE", name: "فنزويلا",             dialCode: "+58"  },
  { code: "VN", name: "فيتنام",              dialCode: "+84"  },
];

export default COUNTRIES;
