// قائمة الدول — الدول العربية أولاً ثم بقية العالم أبجدياً
const COUNTRIES = [
  // الدول العربية
  { code: "SA", name: "السعودية" },
  { code: "JO", name: "الأردن" },
  { code: "PS", name: "فلسطين" },
  { code: "AE", name: "الإمارات" },
  { code: "KW", name: "الكويت" },
  { code: "QA", name: "قطر" },
  { code: "BH", name: "البحرين" },
  { code: "OM", name: "عُمان" },
  { code: "YE", name: "اليمن" },
  { code: "IQ", name: "العراق" },
  { code: "SY", name: "سوريا" },
  { code: "LB", name: "لبنان" },
  { code: "EG", name: "مصر" },
  { code: "LY", name: "ليبيا" },
  { code: "TN", name: "تونس" },
  { code: "DZ", name: "الجزائر" },
  { code: "MA", name: "المغرب" },
  { code: "SD", name: "السودان" },
  { code: "MR", name: "موريتانيا" },
  { code: "SO", name: "الصومال" },
  { code: "DJ", name: "جيبوتي" },
  { code: "KM", name: "جزر القمر" },
  // فاصل
  { code: "", name: "──────────────" },
  // بقية العالم أبجدياً
  { code: "AF", name: "أفغانستان" },
  { code: "AL", name: "ألبانيا" },
  { code: "DE", name: "ألمانيا" },
  { code: "AR", name: "الأرجنتين" },
  { code: "AM", name: "أرمينيا" },
  { code: "AU", name: "أستراليا" },
  { code: "AT", name: "النمسا" },
  { code: "AZ", name: "أذربيجان" },
  { code: "BD", name: "بنغلاديش" },
  { code: "BE", name: "بلجيكا" },
  { code: "BO", name: "بوليفيا" },
  { code: "BA", name: "البوسنة والهرسك" },
  { code: "BR", name: "البرازيل" },
  { code: "BG", name: "بلغاريا" },
  { code: "CA", name: "كندا" },
  { code: "CL", name: "تشيلي" },
  { code: "CN", name: "الصين" },
  { code: "CO", name: "كولومبيا" },
  { code: "HR", name: "كرواتيا" },
  { code: "CZ", name: "التشيك" },
  { code: "DK", name: "الدنمارك" },
  { code: "EC", name: "الإكوادور" },
  { code: "ET", name: "إثيوبيا" },
  { code: "FI", name: "فنلندا" },
  { code: "FR", name: "فرنسا" },
  { code: "GE", name: "جورجيا" },
  { code: "GH", name: "غانا" },
  { code: "GR", name: "اليونان" },
  { code: "GT", name: "غواتيمالا" },
  { code: "HU", name: "المجر" },
  { code: "IN", name: "الهند" },
  { code: "ID", name: "إندونيسيا" },
  { code: "IR", name: "إيران" },
  { code: "IE", name: "أيرلندا" },
  { code: "IL", name: "إسرائيل" },
  { code: "IT", name: "إيطاليا" },
  { code: "JP", name: "اليابان" },
  { code: "KZ", name: "كازاخستان" },
  { code: "KE", name: "كينيا" },
  { code: "KR", name: "كوريا الجنوبية" },
  { code: "MX", name: "المكسيك" },
  { code: "ML", name: "مالي" },
  { code: "MY", name: "ماليزيا" },
  { code: "MX", name: "المكسيك" },
  { code: "NL", name: "هولندا" },
  { code: "NZ", name: "نيوزيلندا" },
  { code: "NG", name: "نيجيريا" },
  { code: "NO", name: "النرويج" },
  { code: "PK", name: "باكستان" },
  { code: "PE", name: "بيرو" },
  { code: "PH", name: "الفلبين" },
  { code: "PL", name: "بولندا" },
  { code: "PT", name: "البرتغال" },
  { code: "RO", name: "رومانيا" },
  { code: "RU", name: "روسيا" },
  { code: "SN", name: "السنغال" },
  { code: "RS", name: "صربيا" },
  { code: "SG", name: "سنغافورة" },
  { code: "ZA", name: "جنوب أفريقيا" },
  { code: "ES", name: "إسبانيا" },
  { code: "SE", name: "السويد" },
  { code: "CH", name: "سويسرا" },
  { code: "TZ", name: "تنزانيا" },
  { code: "TH", name: "تايلاند" },
  { code: "TR", name: "تركيا" },
  { code: "UA", name: "أوكرانيا" },
  { code: "GB", name: "المملكة المتحدة" },
  { code: "US", name: "الولايات المتحدة" },
  { code: "UZ", name: "أوزبكستان" },
  { code: "VE", name: "فنزويلا" },
  { code: "VN", name: "فيتنام" },
];

export default COUNTRIES;
